version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    image: backend
    volumes:
      - pars_app:/frontend/public/uploads
    networks:
      - app-network
  db:
    image: db
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_HOST: localhost
    ports:
      - "3306:3306"
    networks:
      - app-network
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    image: frontend
    volumes:
      - pars_app:/frontend/public/uploads
    networks:
      - app-network
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    build:
      context: ./
      dockerfile: ./jenkins/Dockerfile
    ports:
     - '8080:8080'
     - '50000:50000'
    container_name: jenkins
  agent:
    image: jenkins/ssh-agent:jdk17
    privileged: true
    user: root
    container_name: agent
    expose:
    - 22
    environment:
    - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTemssygT/LhZzc0KU0lCplWVNZBHJhNiDdsFATJC+9tUoCqjis9NZEfAFA1zD6PGol0WbHkWUQGxvIPUYlYiiH/rdt9MV2fI31dtVeUYbWfYzKr9Cjvt8TXX/b+FXmDRRuRJ6rLWDoxBLRLjVNVKG1KUV/d+fDvjR1s6pcMtU2mD1Wwbflbuy6L1f5SNt60R5YeBeNja5UPAftk8/X/YYsfbyZ38kPZxXwyB7JijSweW12lixnpWGIlX+0cpOP1Z7AFFaBo2JvomWmbSkttqK7AhwT3iVgdIOZoc+D33KH4rkDURWPq39atqFIA7rCbKzcwhCvgAhScSwArIvLAIURD+wIVs8N9kj20wydLNSoa2+EAjnaSB9tdXjqa7MabXb0KQXBmSGnG5c+J8NAjgq06/pxrnkQsgb+EqPT0pLnpx4hVS+U//0GExIJXuKWokz7whJe/P7kmYjbUPLgf6YuvFJSlEnazQTD6IDfFGj9Lek+5C56YClZExpju46lq0= lolke@MainDescktop
    entrypoint: >
      /bin/bash -c "apt-get update && \
                        apt-get install -y awscli docker.io && \
                        apt-get clean"

volumes:
  pars_app:

networks:
  app-network:
    driver: bridge
    external: false