version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    image: backend
    volumes:
      - pars_app:/frontend/public/uploads
    networks:
      - app-network
  db:
    image: db
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_HOST: localhost
    ports:
      - "3306:3306"
    networks:
      - app-network
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    image: frontend
    volumes:
      - pars_app:/frontend/public/uploads
    networks:
      - app-network

volumes:
  pars_app:

networks:
  app-network:
    driver: bridge
    external: false