version: '3'
services:
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_HOST: localhost
    ports:
      - "3306:3306"
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'