version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
    image: backend
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_HOST: localhost
    ports:
      - "3306:3306"
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    image: frontend