"""Add new preview

Revision ID: 1be877dc9c40
Revises: 8629cf33695d
Create Date: 2022-06-06 12:36:17.541824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1be877dc9c40'
down_revision = '8629cf33695d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('imgs', sa.Text(), nullable=False))
    op.alter_column('news', 'editor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('news', 'preview')
    op.drop_column('news', 'img_name')
    op.add_column('news_preview', sa.Column('img', sa.Text(), nullable=False))
    op.add_column('news_preview', sa.Column('news_id', sa.Integer(), nullable=False))
    op.drop_constraint('news_preview_ibfk_1', 'news_preview', type_='foreignkey')
    op.create_foreign_key(None, 'news_preview', 'news', ['news_id'], ['id'])
    op.drop_column('news_preview', 'editor_id')
    op.drop_column('news_preview', 'posted_at')
    op.drop_column('news_preview', 'img_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_preview', sa.Column('img_name', mysql.TEXT(), nullable=False))
    op.add_column('news_preview', sa.Column('posted_at', mysql.TIME(), nullable=False))
    op.add_column('news_preview', sa.Column('editor_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news_preview', type_='foreignkey')
    op.create_foreign_key('news_preview_ibfk_1', 'news_preview', 'editor', ['editor_id'], ['profile_id'])
    op.drop_column('news_preview', 'news_id')
    op.drop_column('news_preview', 'img')
    op.add_column('news', sa.Column('img_name', mysql.TEXT(), nullable=False))
    op.add_column('news', sa.Column('preview', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('news', 'editor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('news', 'imgs')
    # ### end Alembic commands ###
