"""Remove news_id from preview add preview_id to news

Revision ID: 1fde967c370c
Revises: 34db9c79f2f7
Create Date: 2022-06-07 08:13:34.737950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fde967c370c'
down_revision = '34db9c79f2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('preview_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'news_preview', ['preview_id'], ['id'])
    op.drop_constraint('news_preview_ibfk_1', 'news_preview', type_='foreignkey')
    op.drop_column('news_preview', 'news_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_preview', sa.Column('news_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('news_preview_ibfk_1', 'news_preview', 'news', ['news_id'], ['id'])
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'preview_id')
    # ### end Alembic commands ###
