"""Change preview column nullable

Revision ID: 34db9c79f2f7
Revises: 1be877dc9c40
Create Date: 2022-06-06 12:38:14.696353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34db9c79f2f7'
down_revision = '1be877dc9c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_preview', 'news_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_preview', 'news_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
