"""Remove imgs colum from news

Revision ID: 7507521688d8
Revises: bbcd2ee32717
Create Date: 2022-06-10 11:48:49.166173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7507521688d8'
down_revision = 'bbcd2ee32717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'imgs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('imgs', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
