"""empty message

Revision ID: 9a6017112270
Revises: 4c96963f827d
Create Date: 2023-06-15 07:42:54.294030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a6017112270'
down_revision = '4c96963f827d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editor')
    op.drop_index('username', table_name='profile')
    op.drop_table('profile')
    op.alter_column('news_preview', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('role', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'description')
    op.alter_column('news_preview', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_table('profile',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'profile', ['username'], unique=False)
    op.create_table('editor',
    sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='editor_ibfk_1'),
    sa.PrimaryKeyConstraint('profile_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
