"""Add editor id in news

Revision ID: b2113fad9f6d
Revises: 
Create Date: 2022-05-27 08:17:00.984494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2113fad9f6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('editor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'news', 'editor', ['editor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'editor_id')
    # ### end Alembic commands ###
