pipeline {
    agent any
    triggers {
        pollSCM '*/5 * * * *'
    }
    environment {
        AWS_REGION = 'eu-central-1'
        AWS_ACCOUNT_ID = '361769559551'
        ECR_REPOSITORY_1 = 'my-backend-repo'
        ECR_REPOSITORY_2 = 'my-frontend-repo'
        IMAGE_TAG_1 = "${env.BUILD_NUMBER}"
        IMAGE_TAG_2 = "${env.BUILD_NUMBER}"
        AWS_CREDENTIALS = '361769559551'
    }
    stages {
        stage('Check Tools') {
            steps {
                sh '''
                    echo "Перевірка AWS CLI та Docker"
                    aws --version || echo "AWS CLI не доступний"
                    docker --version || echo "Docker не доступний"
                '''
            }
        }
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Login to AWS ECR') {
            steps {
                withCredentials([aws(credentialsId: '361769559551)']) {
                    sh '''
                        aws ecr get-login-password --region ${AWS_REGION} | \
                        docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                    '''
                    }
            }
        }

        stage('Push Docker Images') {
            steps {
                script {

                    docker.withRegistry('tcp://localhost:2375', "https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_1}", '361769559551') {
                        docker.image("backend").push("${IMAGE_TAG_1}")
                    }


                    docker.withRegistry('tcp://localhost:2375', "https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_2}", '361769559551') {
                        docker.image("frontend").push("${IMAGE_TAG_2}")
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}