pipeline {
    agent any
    triggers {
        pollSCM '*/5 * * * *'
    }
    environment {
        AWS_REGION = 'eu-central-1'
        AWS_ACCOUNT_ID = '361769559551'
        BACKEND_REPOSITORY = 'my-backend-repo'
        FRONTEND_REPOSITORY = 'my-frontend-repo'
        IMAGE_TAG = "latest"
        AWS_CREDENTIALS = "ecr:eu-central-1:aws-credentials"
    }
    stages {
        stage('Check Tools') {
            steps {
                sh '''
                    echo "Перевірка AWS CLI та Docker"
                    aws --version || echo "AWS CLI не доступний"
                    docker --version || echo "Docker не доступний"
                '''
            }
        }
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Login to AWS ECR') {
            steps {
                sh '''
                    echo "Логін до AWS ECR"
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }
        stage('Build Docker Images') {
            steps {
                script {
                    sh 'docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPOSITORY}:${IMAGE_TAG} ./backend'
                    sh 'docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPOSITORY}:${IMAGE_TAG} ./frontend'
                }
            }
        }
        stage('Push Docker Images') {
            steps {
                script {
                    sh 'docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPOSITORY}:${IMAGE_TAG}'
                    sh 'docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPOSITORY}:${IMAGE_TAG}'
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
