pipeline {
    agent {
        node{
            label 'jenkins_agent'
        }
    }
    triggers {
        pollSCM '*/5 * * * *'
    }
    environment {
        AWS_REGION = 'eu-central-1'  // Вкажіть ваш регіон AWS
        AWS_ACCOUNT_ID = '361769559551'  // Замініть на ваш AWS Account ID
        ECR_REPOSITORY_1 = 'my-backend-repo'  // Назва першого ECR репозиторію
        ECR_REPOSITORY_2 = 'my-frontend-repo'  // Назва другого ECR репозиторію
        IMAGE_TAG_1 = "${env.BUILD_NUMBER}"  // Тег з номером білду
        IMAGE_TAG_2 = "${env.BUILD_NUMBER}"  // Тег з номером білду
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Images') {
            steps {
                script {
                    // Збірка першого образу
                    docker.build("${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_1}:${IMAGE_TAG_1}")

                    // Збірка другого образу
                    docker.build("${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_2}:${IMAGE_TAG_2}")
                }
            }
        }

        stage('Login to AWS ECR') {
            steps {
                sh '''
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }

        stage('Push Docker Images') {
            steps {
                script {
                    // Пуш першого образу
                    docker.withRegistry("https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com") {
                        docker.image("${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_1}:${IMAGE_TAG_1}").push()
                    }

                    // Пуш другого образу
                    docker.withRegistry("https://${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com") {
                        docker.image("${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_2}:${IMAGE_TAG_2}").push()
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}